fuzzy-error-logs.txt

Successes: 6
Errors: 17
Command:
bosh exec launch dipy_deterministic_tracking.json example_invocation.json -v /data/:/data/ -v ${PWD}:${PWD}

Unique errors:
Traceback (most recent call last):
  File "/opt/dipy_deterministic_tracking.py", line 234, in <module>
    main()
  File "/opt/dipy_deterministic_tracking.py", line 209, in main
    fibers, plot=results.streamline_plot)
  File "/opt/dipy_deterministic_tracking.py", line 77, in dwi_deterministic_tracing
    affine=np.eye(4), step_size=0.5)
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/local/localtracking.py", line 89, in __init__
    self._voxel_size = np.ascontiguousarray(self._get_voxel_size(affine),
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/local/localtracking.py", line 32, in _get_voxel_size
    if not np.allclose(np.triu(dotlin, 1), 0., atol=1e-5):
  File "<__array_function__ internals>", line 6, in triu
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/twodim_base.py", line 467, in triu
    return where(mask, zeros(1, m.dtype), m)
  File "<__array_function__ internals>", line 6, in where
ValueError: operands could not be broadcast together with shapes (4,3) (1,) (3,3)

Traceback (most recent call last):
  File "/opt/dipy_deterministic_tracking.py", line 234, in <module>
    main()
  File "/opt/dipy_deterministic_tracking.py", line 209, in main
    fibers, plot=results.streamline_plot)
  File "/opt/dipy_deterministic_tracking.py", line 73, in dwi_deterministic_tracing
    affine=np.eye(4))
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/utils.py", line 390, in seeds_from_mask
    grid = np.mgrid[0:density[0], 0:density[1], 0:density[2]]
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/index_tricks.py", line 173, in __getitem__
    nn = _nx.indices(size, typ)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/numeric.py", line 1712, in indices
    shape[:i] + (dim,) + shape[i+1:]
ValueError: cannot reshape array of size 4 into shape (3,1,1)

Traceback (most recent call last):
  File "/opt/dipy_deterministic_tracking.py", line 234, in <module>
    main()
  File "/opt/dipy_deterministic_tracking.py", line 209, in main
    fibers, plot=results.streamline_plot)
  File "/opt/dipy_deterministic_tracking.py", line 77, in dwi_deterministic_tracing
    affine=np.eye(4), step_size=0.5)
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/local/localtracking.py", line 89, in __init__
    self._voxel_size = np.ascontiguousarray(self._get_voxel_size(affine),
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/local/localtracking.py", line 32, in _get_voxel_size
    if not np.allclose(np.triu(dotlin, 1), 0., atol=1e-5):
  File "<__array_function__ internals>", line 6, in triu
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/twodim_base.py", line 467, in triu
    return where(mask, zeros(1, m.dtype), m)
  File "<__array_function__ internals>", line 6, in where
ValueError: operands could not be broadcast together with shapes (3,4) (1,) (3,3)

Traceback (most recent call last):
  File "/opt/dipy_deterministic_tracking.py", line 234, in <module>
    main()
  File "/opt/dipy_deterministic_tracking.py", line 209, in main
    fibers, plot=results.streamline_plot)
  File "/opt/dipy_deterministic_tracking.py", line 73, in dwi_deterministic_tracing
    affine=np.eye(4))
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/utils.py", line 390, in seeds_from_mask
    grid = np.mgrid[0:density[0], 0:density[1], 0:density[2]]
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/index_tricks.py", line 173, in __getitem__
    nn = _nx.indices(size, typ)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/numeric.py", line 1712, in indices
    shape[:i] + (dim,) + shape[i+1:]
ValueError: cannot reshape array of size 4 into shape (1,1,3)

Traceback (most recent call last):
  File "/opt/dipy_deterministic_tracking.py", line 234, in <module>
    main()
  File "/opt/dipy_deterministic_tracking.py", line 209, in main
    fibers, plot=results.streamline_plot)
  File "/opt/dipy_deterministic_tracking.py", line 73, in dwi_deterministic_tracing
    affine=np.eye(4))
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/utils.py", line 390, in seeds_from_mask
    grid = np.mgrid[0:density[0], 0:density[1], 0:density[2]]
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/index_tricks.py", line 173, in __getitem__
    nn = _nx.indices(size, typ)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/numeric.py", line 1712, in indices
    shape[:i] + (dim,) + shape[i+1:]
ValueError: cannot reshape array of size 4 into shape (1,3,1)

Traceback (most recent call last):
  File "/opt/dipy_deterministic_tracking.py", line 234, in <module>
    main()
  File "/opt/dipy_deterministic_tracking.py", line 209, in main
    fibers, plot=results.streamline_plot)
  File "/opt/dipy_deterministic_tracking.py", line 73, in dwi_deterministic_tracing
    affine=np.eye(4))
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/utils.py", line 390, in seeds_from_mask
    grid = np.mgrid[0:density[0], 0:density[1], 0:density[2]]
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/index_tricks.py", line 173, in __getitem__
    nn = _nx.indices(size, typ)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/numeric.py", line 1712, in indices
    shape[:i] + (dim,) + shape[i+1:]
ValueError: cannot reshape array of size 3 into shape (1,2,1)

Traceback (most recent call last):
  File "/opt/dipy_deterministic_tracking.py", line 234, in <module>
    main()
  File "/opt/dipy_deterministic_tracking.py", line 209, in main
    fibers, plot=results.streamline_plot)
  File "/opt/dipy_deterministic_tracking.py", line 78, in dwi_deterministic_tracing
    streamlines = Streamlines(streamlines_generator)
  File "/usr/local/lib/python3.6/site-packages/nibabel/streamlines/array_sequence.py", line 103, in __init__
    self.extend(iterable)
  File "/usr/local/lib/python3.6/site-packages/nibabel/streamlines/array_sequence.py", line 250, in extend
    for e in elements:
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/utils.py", line 957, in move_streamlines
    for sl in streamlines:
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/local/localtracking.py", line 131, in _generate_streamlines
    directions = self.direction_getter.initial_direction(s)
  File "dipy/reconst/peak_direction_getter.pyx", line 75, in dipy.reconst.peak_direction_getter.PeaksAndMetricsDirectionGetter.initial_direction
IndexError: point outside data

Traceback (most recent call last):
  File "/opt/dipy_deterministic_tracking.py", line 234, in <module>
    main()
  File "/opt/dipy_deterministic_tracking.py", line 209, in main
    fibers, plot=results.streamline_plot)
  File "/opt/dipy_deterministic_tracking.py", line 73, in dwi_deterministic_tracing
    affine=np.eye(4))
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/utils.py", line 390, in seeds_from_mask
    grid = np.mgrid[0:density[0], 0:density[1], 0:density[2]]
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/index_tricks.py", line 173, in __getitem__
    nn = _nx.indices(size, typ)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/numeric.py", line 1712, in indices
    shape[:i] + (dim,) + shape[i+1:]
ValueError: cannot reshape array of size 3 into shape (2,1,1)

Traceback (most recent call last):
  File "/opt/dipy_deterministic_tracking.py", line 234, in <module>
    main()
  File "/opt/dipy_deterministic_tracking.py", line 209, in main
    fibers, plot=results.streamline_plot)
  File "/opt/dipy_deterministic_tracking.py", line 73, in dwi_deterministic_tracing
    affine=np.eye(4))
  File "/usr/local/lib/python3.6/site-packages/dipy/tracking/utils.py", line 390, in seeds_from_mask
    grid = np.mgrid[0:density[0], 0:density[1], 0:density[2]]
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/index_tricks.py", line 173, in __getitem__
    nn = _nx.indices(size, typ)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/numeric.py", line 1712, in indices
    shape[:i] + (dim,) + shape[i+1:]
ValueError: cannot reshape array of size 3 into shape (1,1,2)